# ----------------------------------------------------------------------------
# Copyright (c) 2026, QIIME 2 development team.
#
# Distributed under the terms of the Lesser General Public License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------

from q2_types.feature_data import FeatureData
from q2_types.feature_table import FeatureTable, Frequency
from q2_types.genome_data import GenomeData, Loci
from qiime2.plugin import (
    Bool,
    Categorical,
    Choices,
    Citations,
    Float,
    Int,
    List,
    Metadata,
    MetadataColumn,
    Plugin,
    Str,
    Visualization,
)
from rachis.core.type import Range

from q2_deseq2 import __version__
from q2_deseq2.methods import (
    _estimate_differential_expression,
    _estimate_model,
)
from q2_deseq2.pipelines import estimate, estimate_model
from q2_deseq2.types import DESeq2Run, DESeq2Stats
from q2_deseq2.types import (
    DESeq2RunDirectoryFormat,
    DESeq2RunMetadataFormat,
    DESeq2StatsDirectoryFormat,
    DESeq2StatsFormat,
)
from q2_deseq2.visualizers import _visualize

citations = Citations.load("citations.bib", package="q2_deseq2")

plugin = Plugin(
    name="deseq2",
    version=__version__,
    website="https://github.com/bokulich-lab/q2-deseq2",
    package="q2_deseq2",
    description="QIIME 2 plugin for differential abundance analysis with DESeq2.",
    short_description="DESeq2 integration for QIIME 2.",
    citations=[citations["Love-2014"]],
)

plugin.register_semantic_types(DESeq2Stats, DESeq2Run)
plugin.register_formats(
    DESeq2StatsFormat,
    DESeq2StatsDirectoryFormat,
    DESeq2RunMetadataFormat,
    DESeq2RunDirectoryFormat,
)
plugin.register_artifact_class(
    FeatureData[DESeq2Stats],
    DESeq2StatsDirectoryFormat,
    description="Differential expression statistics generated by DESeq2.",
)
plugin.register_artifact_class(
    DESeq2Run,
    DESeq2RunDirectoryFormat,
    description="Internal DESeq2 run outputs used to build visualizations without rerunning DESeq2.",
)

plugin.methods.register_function(
    function=_estimate_differential_expression,
    inputs={"table": FeatureTable[Frequency]},
    parameters={
        "condition": MetadataColumn[Categorical],
        "reference_level": Str,
        "min_total_count": Int % Range(0, None),
        "fit_type": Str % Choices("parametric", "local", "mean"),
        "size_factor_type": Str % Choices("ratio", "poscounts", "iterate"),
        "alpha": Float % Range(0.0, 1.0),
        "cooks_cutoff": Bool,
        "independent_filtering": Bool,
    },
    outputs=[("deseq2_stats", FeatureData[DESeq2Stats]), ("deseq2_results", DESeq2Run)],
    input_descriptions={"table": "A per-sample gene count feature table."},
    parameter_descriptions={
        "condition": (
            "Categorical sample metadata column defining experimental condition. "
            "At least two levels are required."
        ),
        "reference_level": (
            "Condition level to use as the reference baseline for all pairwise contrasts. "
            "If omitted, inferred for two-level designs and required when more than two "
            "levels are present."
        ),
        "min_total_count": "Filter out genes with total count below this threshold before DESeq2.",
        "fit_type": "DESeq2 dispersion fit type.",
        "size_factor_type": "DESeq2 size-factor estimation type.",
        "alpha": "Adjusted p-value cutoff used by DESeq2 for significance summaries.",
        "cooks_cutoff": "Use Cook's distance cutoff in DESeq2 result filtering.",
        "independent_filtering": "Enable DESeq2 independent filtering.",
    },
    output_descriptions={
        "deseq2_stats": (
            "Tabular DESeq2 statistics per gene and comparison including effect size and "
            "significance metrics."
        ),
        "deseq2_results": (
            "Internal DESeq2 run outputs including normalized counts and summaries."
        ),
    },
    name="Estimate differential expression with DESeq2.",
    description=(
        "Run DESeq2 differential expression on a feature table and return the "
        "feature-level statistics artifact plus an internal run artifact."
    ),
    citations=[citations["Love-2014"]],
)

plugin.methods.register_function(
    function=_estimate_model,
    inputs={"table": FeatureTable[Frequency]},
    parameters={
        "metadata": Metadata,
        "fixed_effects_formula": Str,
        "reference_levels": List[Str],
        "effect_specs": List[Str],
        "test": Str % Choices("wald", "lrt"),
        "reduced_formula": Str,
        "min_total_count": Int % Range(0, None),
        "fit_type": Str % Choices("parametric", "local", "mean"),
        "size_factor_type": Str % Choices("ratio", "poscounts", "iterate"),
        "alpha": Float % Range(0.0, 1.0),
        "cooks_cutoff": Bool,
        "independent_filtering": Bool,
    },
    outputs=[("deseq2_stats", FeatureData[DESeq2Stats]), ("deseq2_results", DESeq2Run)],
    input_descriptions={"table": "A per-sample gene count feature table."},
    parameter_descriptions={
        "metadata": "Sample metadata used to construct the DESeq2 design matrix.",
        "fixed_effects_formula": (
            "R-style fixed-effects design formula without the response term, "
            "for example 'genotype + treatment + genotype:treatment'."
        ),
        "reference_levels": (
            "Categorical releveling directives of the form 'column::level'. "
            "Each listed level becomes the reference baseline for its metadata column."
        ),
        "effect_specs": (
            "Requested model effects to extract. Supported forms are "
            "'coef::<resultsName>', "
            "'contrast::<factor>::<numerator>::<denominator>', and "
            "'simple::<factor>::<numerator>::<denominator>|within::<factor>::<level>'. "
            "If omitted for Wald tests, all non-intercept coefficients are returned."
        ),
        "test": (
            "DESeq2 test to run. Use 'wald' for coefficient and contrast testing or "
            "'lrt' for likelihood-ratio testing against a reduced model."
        ),
        "reduced_formula": (
            "Reduced model formula used when test='lrt'. Leave empty for Wald tests."
        ),
        "min_total_count": "Filter out genes with total count below this threshold before DESeq2.",
        "fit_type": "DESeq2 dispersion fit type.",
        "size_factor_type": "DESeq2 size-factor estimation type.",
        "alpha": "Adjusted p-value cutoff used by DESeq2 for significance summaries.",
        "cooks_cutoff": "Use Cook's distance cutoff in DESeq2 result filtering.",
        "independent_filtering": "Enable DESeq2 independent filtering.",
    },
    output_descriptions={
        "deseq2_stats": (
            "Tabular DESeq2 statistics per gene and extracted model effect including "
            "effect size and significance metrics."
        ),
        "deseq2_results": (
            "Internal DESeq2 run outputs including normalized counts, fitted-model "
            "metadata, and effect summaries."
        ),
    },
    name="Estimate a multi-factor DESeq2 model.",
    description=(
        "Run DESeq2 using full sample metadata plus a fixed-effects formula and "
        "return both the feature-level statistics artifact and an internal run artifact."
    ),
    citations=[citations["Love-2014"]],
)

plugin.visualizers.register_function(
    function=_visualize,
    inputs={
        "deseq2_results": DESeq2Run,
        "gene_annotations": GenomeData[Loci],
    },
    input_descriptions={
        "deseq2_results": (
            "Internal DESeq2 run artifact containing result tables and normalized counts."
        ),
        "gene_annotations": (
            "Optional GenomeData[Loci] annotations in GFF3 format. "
            "When provided, gene names/products are merged into report outputs."
        ),
    },
    parameters={
        "reference_id": Str,
    },
    parameter_descriptions={
        "reference_id": "ID of the reference genome containing the annotations.",
    },
    name="Visualize the differential expression from DESeq2 results.",
    description=(
        "Write a DESeq2 differential expression visualization from a precomputed "
        "internal run artifact."
    ),
    citations=[citations["Love-2014"]],
)

plugin.pipelines.register_function(
    function=estimate,
    inputs={"table": FeatureTable[Frequency], "gene_annotations": GenomeData[Loci]},
    parameters={
        "reference_id": Str,
        "condition": MetadataColumn[Categorical],
        "reference_level": Str,
        "min_total_count": Int,
        "fit_type": Str % Choices("parametric", "local", "mean"),
        "size_factor_type": Str % Choices("ratio", "poscounts", "iterate"),
        "alpha": Float,
        "cooks_cutoff": Bool,
        "independent_filtering": Bool,
    },
    outputs=[
        ("expression_stats", FeatureData[DESeq2Stats]),
        ("visualization", Visualization),
    ],
    input_descriptions={
        "table": "A per-sample gene count feature table.",
        "gene_annotations": (
            "Optional GenomeData[Loci] annotations in GFF3 format. "
            "When provided, gene names/products are merged into report outputs."
        ),
    },
    parameter_descriptions={
        "reference_id": "ID of the reference genome containing the annotations.",
        "condition": (
            "Categorical sample metadata column defining experimental condition. "
            "At least two levels are required."
        ),
        "reference_level": (
            "Condition level to use as the reference baseline for all pairwise contrasts. "
            "If omitted, inferred for two-level designs and required when more than two "
            "levels are present."
        ),
        "min_total_count": "Filter out genes with total count below this threshold before DESeq2.",
        "fit_type": "DESeq2 dispersion fit type.",
        "size_factor_type": "DESeq2 size-factor estimation type.",
        "alpha": "Adjusted p-value cutoff used by DESeq2 for significance summaries.",
        "cooks_cutoff": "Use Cook's distance cutoff in DESeq2 result filtering.",
        "independent_filtering": "Enable DESeq2 independent filtering.",
    },
    output_descriptions={
        "expression_stats": (
            "Tabular DESeq2 statistics per gene and comparison including effect size and "
            "significance metrics."
        ),
        "visualization": ("Differential expression results visualization."),
    },
    name="Estimate differential expression with DESeq2.",
    description=(
        "Run DESeq2 differential expression and return both the "
        "feature-level statistics artifact and a visualization."
    ),
    citations=[citations["Love-2014"]],
)

plugin.pipelines.register_function(
    function=estimate_model,
    inputs={"table": FeatureTable[Frequency], "gene_annotations": GenomeData[Loci]},
    parameters={
        "reference_id": Str,
        "metadata": Metadata,
        "fixed_effects_formula": Str,
        "reference_levels": List[Str],
        "effect_specs": List[Str],
        "test": Str % Choices("wald", "lrt"),
        "reduced_formula": Str,
        "min_total_count": Int,
        "fit_type": Str % Choices("parametric", "local", "mean"),
        "size_factor_type": Str % Choices("ratio", "poscounts", "iterate"),
        "alpha": Float,
        "cooks_cutoff": Bool,
        "independent_filtering": Bool,
    },
    outputs=[
        ("expression_stats", FeatureData[DESeq2Stats]),
        ("visualization", Visualization),
    ],
    input_descriptions={
        "table": "A per-sample gene count feature table.",
        "gene_annotations": (
            "Optional GenomeData[Loci] annotations in GFF3 format. "
            "When provided, gene names/products are merged into report outputs."
        ),
    },
    parameter_descriptions={
        "reference_id": "ID of the reference genome containing the annotations.",
        "metadata": "Sample metadata used to construct the DESeq2 design matrix.",
        "fixed_effects_formula": (
            "R-style fixed-effects design formula without the response term, "
            "for example 'genotype + treatment + genotype:treatment'."
        ),
        "reference_levels": (
            "Categorical releveling directives of the form 'column::level'. "
            "Each listed level becomes the reference baseline for its metadata column."
        ),
        "effect_specs": (
            "Requested model effects to extract. Supported forms are "
            "'coef::<resultsName>', "
            "'contrast::<factor>::<numerator>::<denominator>', and "
            "'simple::<factor>::<numerator>::<denominator>|within::<factor>::<level>'."
        ),
        "test": (
            "DESeq2 test to run. Use 'wald' for coefficient and contrast testing or "
            "'lrt' for likelihood-ratio testing against a reduced model."
        ),
        "reduced_formula": (
            "Reduced model formula used when test='lrt'. Leave empty for Wald tests."
        ),
        "min_total_count": "Filter out genes with total count below this threshold before DESeq2.",
        "fit_type": "DESeq2 dispersion fit type.",
        "size_factor_type": "DESeq2 size-factor estimation type.",
        "alpha": "Adjusted p-value cutoff used by DESeq2 for significance summaries.",
        "cooks_cutoff": "Use Cook's distance cutoff in DESeq2 result filtering.",
        "independent_filtering": "Enable DESeq2 independent filtering.",
    },
    output_descriptions={
        "expression_stats": (
            "Tabular DESeq2 statistics per gene and extracted model effect including "
            "effect size and significance metrics."
        ),
        "visualization": ("Differential expression results visualization."),
    },
    name="Estimate a multi-factor DESeq2 model and visualize the results.",
    description=(
        "Run DESeq2 using full sample metadata plus a fixed-effects formula and "
        "return both the feature-level statistics artifact and a visualization."
    ),
    citations=[citations["Love-2014"]],
)

# Import transformers at module import-time so registration decorators execute.
import q2_deseq2.types._transformers  # noqa: E402,F401
