# ----------------------------------------------------------------------------
# Copyright (c) 2024, Michal Ziemski.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------

from qiime2.plugin import (
    Bool,
    Categorical,
    Choices,
    Citations,
    Float,
    Int,
    MetadataColumn,
    Plugin,
    Str,
    Visualization,
)
from q2_types.feature_data import FeatureData
from q2_types.feature_table import FeatureTable, Frequency
from q2_types.genome_data import GenomeData, Loci
from rachis.core.type import Range

from q2_deseq2 import __version__
from q2_deseq2.types import (
    DESeq2ImageFormat,
    DESeq2RunDirectoryFormat,
    DESeq2RunMetadataFormat,
    DESeq2StatsDirectoryFormat,
    DESeq2StatsFormat,
)
from q2_deseq2.methods import (
    _estimate_differential_expression,
)
from q2_deseq2.pipelines import estimate
from q2_deseq2.types import DESeq2Run, DESeq2Stats
from q2_deseq2.visualizers import _visualize

citations = Citations.load("citations.bib", package="q2_deseq2")

plugin = Plugin(
    name="deseq2",
    version=__version__,
    website="https://github.com/bokulich-lab/q2-deseq2",
    package="q2_deseq2",
    description="QIIME 2 plugin for differential abundance analysis with DESeq2.",
    short_description="DESeq2 integration for QIIME 2.",
    citations=[citations["Love-2014"]],
)

plugin.register_semantic_types(DESeq2Stats, DESeq2Run)
plugin.register_formats(
    DESeq2StatsFormat,
    DESeq2StatsDirectoryFormat,
    DESeq2RunMetadataFormat,
    DESeq2ImageFormat,
    DESeq2RunDirectoryFormat,
)
plugin.register_artifact_class(
    FeatureData[DESeq2Stats],
    DESeq2StatsDirectoryFormat,
    description="Differential expression statistics generated by DESeq2.",
)
plugin.register_artifact_class(
    DESeq2Run,
    DESeq2RunDirectoryFormat,
    description="Internal DESeq2 run outputs used to build visualizations without rerunning DESeq2.",
)

plugin.methods.register_function(
    function=_estimate_differential_expression,
    inputs={"table": FeatureTable[Frequency]},
    parameters={
        "condition": MetadataColumn[Categorical],
        "reference_level": Str,
        "min_total_count": Int % Range(0, None),
        "fit_type": Str % Choices("parametric", "local", "mean"),
        "alpha": Float % Range(0.0, 1.0),
        "cooks_cutoff": Bool,
        "independent_filtering": Bool,
    },
    outputs=[("deseq2_stats", FeatureData[DESeq2Stats]), ("deseq2_results", DESeq2Run)],
    input_descriptions={"table": "A per-sample gene count feature table."},
    parameter_descriptions={
        "condition": (
            "Categorical sample metadata column defining experimental condition. "
            "At least two levels are required."
        ),
        "reference_level": (
            "Condition level to use as the reference baseline for all pairwise contrasts. "
            "If omitted, inferred for two-level designs and required when more than two "
            "levels are present."
        ),
        "min_total_count": "Filter out genes with total count below this threshold before DESeq2.",
        "fit_type": "DESeq2 dispersion fit type.",
        "alpha": "Adjusted p-value cutoff used by DESeq2 for significance summaries.",
        "cooks_cutoff": "Use Cook's distance cutoff in DESeq2 result filtering.",
        "independent_filtering": "Enable DESeq2 independent filtering.",
    },
    output_descriptions={
        "deseq2_stats": (
            "Tabular DESeq2 statistics per gene and comparison including effect size and "
            "significance metrics."
        ),
        "deseq2_results": (
            "Internal DESeq2 run outputs including normalized counts and summaries."
        ),
    },
    name="Estimate differential expression with DESeq2.",
    description=(
        "Run DESeq2 differential expression on a feature table and return the "
        "feature-level statistics artifact plus an internal run artifact."
    ),
    citations=[citations["Love-2014"]],
)

plugin.visualizers.register_function(
    function=_visualize,
    inputs={
        "deseq2_results": DESeq2Run,
        "gene_annotations": GenomeData[Loci],
    },
    input_descriptions={
        "deseq2_results": (
            "Internal DESeq2 run artifact containing result tables and normalized counts."
        ),
        "gene_annotations": (
            "Optional GenomeData[Loci] annotations in GFF3 format. "
            "When provided, gene names/products are merged into report outputs."
        ),
    },
    parameters={
        "reference_id": Str,
    },
    parameter_descriptions={
        "reference_id": "ID of the reference genome containing the annotations.",
    },
    name="Visualize the differential expression from DESeq2 results.",
    description=(
        "Write a DESeq2 differential expression visualization from a precomputed "
        "internal run artifact."
    ),
    citations=[citations["Love-2014"]],
)

plugin.pipelines.register_function(
    function=estimate,
    inputs={"table": FeatureTable[Frequency], "gene_annotations": GenomeData[Loci]},
    parameters={
        "reference_id": Str,
        "condition": MetadataColumn[Categorical],
        "reference_level": Str,
        "min_total_count": Int,
        "fit_type": Str % Choices("parametric", "local", "mean"),
        "alpha": Float,
        "cooks_cutoff": Bool,
        "independent_filtering": Bool,
    },
    outputs=[
        ("expression_stats", FeatureData[DESeq2Stats]),
        ("visualization", Visualization),
    ],
    input_descriptions={
        "table": "A per-sample gene count feature table.",
        "gene_annotations": (
            "Optional GenomeData[Loci] annotations in GFF3 format. "
            "When provided, gene names/products are merged into report outputs."
        ),
    },
    parameter_descriptions={
        "reference_id": "ID of the reference genome containing the annotations.",
        "condition": (
            "Categorical sample metadata column defining experimental condition. "
            "At least two levels are required."
        ),
        "reference_level": (
            "Condition level to use as the reference baseline for all pairwise contrasts. "
            "If omitted, inferred for two-level designs and required when more than two "
            "levels are present."
        ),
        "min_total_count": "Filter out genes with total count below this threshold before DESeq2.",
        "fit_type": "DESeq2 dispersion fit type.",
        "alpha": "Adjusted p-value cutoff used by DESeq2 for significance summaries.",
        "cooks_cutoff": "Use Cook's distance cutoff in DESeq2 result filtering.",
        "independent_filtering": "Enable DESeq2 independent filtering.",
    },
    output_descriptions={
        "expression_stats": (
            "Tabular DESeq2 statistics per gene and comparison including effect size and "
            "significance metrics."
        ),
        "visualization": ("Differential expression results visualization."),
    },
    name="Estimate differential expression with DESeq2.",
    description=(
        "Run DESeq2 differential expression and return both the "
        "feature-level statistics artifact and a visualization."
    ),
    citations=[citations["Love-2014"]],
)

# Import transformers at module import-time so registration decorators execute.
import q2_deseq2.types._transformers  # noqa: E402,F401
