# ----------------------------------------------------------------------------
# Copyright (c) 2024, Michal Ziemski.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------

from qiime2.plugin import (
    Bool, Categorical, Choices, Citations, Float, Int,
    MetadataColumn, Plugin, Str
)
from q2_types.feature_data import FeatureData
from q2_types.feature_table import FeatureTable, Frequency
from q2_deseq2 import __version__
from q2_deseq2._formats import DESeq2StatsDirectoryFormat, DESeq2StatsFormat
from q2_deseq2._methods import differential_expression_table
from q2_deseq2._types import DESeq2Stats
from q2_deseq2._visualizers import differential_expression

citations = Citations.load("citations.bib", package="q2_deseq2")

plugin = Plugin(
    name="deseq2",
    version=__version__,
    website="https://example.com",
    package="q2_deseq2",
    description="A QIIME 2 plugin for differential abundance analysis powered by DESeq2.",
    short_description="DESeq2 integration for QIIME 2.",
    citations=[citations['Caporaso-Bolyen-2024'], citations['Love-2014']]
)

plugin.register_semantic_types(DESeq2Stats)
plugin.register_formats(DESeq2StatsFormat, DESeq2StatsDirectoryFormat)
plugin.register_artifact_class(
    FeatureData[DESeq2Stats],
    DESeq2StatsDirectoryFormat,
    description='Differential expression statistics generated by DESeq2.'
)

plugin.methods.register_function(
    function=differential_expression_table,
    inputs={'table': FeatureTable[Frequency]},
    parameters={
        'condition': MetadataColumn[Categorical],
        'test_level': Str,
        'reference_level': Str,
        'min_total_count': Int,
        'fit_type': Str % Choices('parametric', 'local', 'mean'),
        'alpha': Float,
        'cooks_cutoff': Bool,
        'independent_filtering': Bool
    },
    outputs=[('differential_expression_stats', FeatureData[DESeq2Stats])],
    input_descriptions={
        'table': 'A gene count table where features are genes and samples are RNA-seq samples.'
    },
    parameter_descriptions={
        'condition': ('Categorical sample metadata column defining experimental condition. '
                      'At least two levels are required.'),
        'test_level': ('Condition level to test as numerator in the contrast. '
                       'If omitted, inferred for two-level designs.'),
        'reference_level': ('Condition level to use as denominator in the contrast. '
                            'If omitted, inferred for two-level designs.'),
        'min_total_count': 'Filter out genes with total count below this threshold before DESeq2.',
        'fit_type': 'DESeq2 dispersion fit type.',
        'alpha': 'Adjusted p-value cutoff used by DESeq2 for significance summaries.',
        'cooks_cutoff': 'Use Cook\'s distance cutoff in DESeq2 result filtering.',
        'independent_filtering': 'Enable DESeq2 independent filtering.'
    },
    output_descriptions={
        'differential_expression_stats': (
            'Tabular DESeq2 statistics per gene including effect size and significance metrics.'
        )
    },
    name='Differential expression table (DESeq2)',
    description=('Run DESeq2 differential expression on a feature table and return a '
                 'feature-level statistics artifact.'),
    citations=[citations['Love-2014']]
)

plugin.visualizers.register_function(
    function=differential_expression,
    inputs={'table': FeatureTable[Frequency]},
    parameters={
        'condition': MetadataColumn[Categorical],
        'test_level': Str,
        'reference_level': Str,
        'min_total_count': Int,
        'fit_type': Str % Choices('parametric', 'local', 'mean'),
        'alpha': Float,
        'cooks_cutoff': Bool,
        'independent_filtering': Bool
    },
    input_descriptions={
        'table': 'A gene count table where features are genes and samples are RNA-seq samples.'
    },
    parameter_descriptions={
        'condition': ('Categorical sample metadata column defining experimental condition. '
                      'At least two levels are required.'),
        'test_level': ('Condition level to test as numerator in the contrast. '
                       'If omitted, inferred for two-level designs.'),
        'reference_level': ('Condition level to use as denominator in the contrast. '
                            'If omitted, inferred for two-level designs.'),
        'min_total_count': 'Filter out genes with total count below this threshold before DESeq2.',
        'fit_type': 'DESeq2 dispersion fit type.',
        'alpha': 'Adjusted p-value cutoff used by DESeq2 for significance summaries.',
        'cooks_cutoff': 'Use Cook\'s distance cutoff in DESeq2 result filtering.',
        'independent_filtering': 'Enable DESeq2 independent filtering.'
    },
    name='Differential expression (DESeq2)',
    description=('Run DESeq2 differential expression on a feature table and write a visualization '
                 'containing result tables, normalized counts, an MA plot, and execution logs.'),
    citations=[citations['Love-2014']]
)

# Import transformers at module import-time so registration decorators execute.
import q2_deseq2._transformers  # noqa: E402,F401
